### ISSUE TITLE
Getting error while compiling Unity project after adding AltUnity

### ISSUE THREAD

**Issue by Mayur5712** [jlipps/unity-plugin-workshop#2]
I am trying to build Unity project with AltUnity asset. Before adding AltUnity the project was able to build and I was able to generate APK from it. But after adding AltUnity I started getting below error. 

_Assets/AltUnityTester/AltUnityServer/NewInputSystem.cs(21,23): error CS0246: The type or namespace name 'InputTestFixture' could not be found (are you missing a using directive or an assembly reference?)_

Kindly guide to resolve this issue.

**Comment by jlipps** [comment]
Sorry, I don't generally provide support on this repo. If I knew what this error was about I would help, but I don't have any ideas. I would reach out to AltUnity with this error and see what they say.
