### ISSUE TITLE
Not able to click on Unity elements

### ISSUE THREAD

**Issue by Mayur5712** [jlipps/unity-plugin-workshop#4]
Hi @jlipps , 

We have integrated AltUnity server and trying to integrate appium. 
Setup and everything works well. 
But when we are trying to click on a particular element we are getting error in Appium logs. 

`[debug] [Plugin [altunity]] {"messageId":"1657274332499","commandName":"tapCoordinates","error":null,"data":"\"Finished\"","isNotification":false}
info Appium Command 'click' was *not* handled by the following behaviours or plugins, even though they were registered to handle it: ["default"]. The command *was* handled by these: ["altunity"].`

[appium.log](https://github.com/jlipps/unity-plugin-workshop/files/9071065/appium.log)

**Comment by jlipps** [comment]
This is not an error. This is letting you know that the plugin handled the click command instead of the driver.
