### ISSUE TITLE
Need some info about unity-plugin

### ISSUE THREAD

**Issue by Mayur5712** [jlipps/unity-plugin-workshop#5]
Hi @jlipps ,

I have few queries regarding unity-plugin automation. I would appreciate your help in this.
1. How can we use unity-plugin for iOS platform?
2. Does this integration (Appium 2.0 & AltUnity server) works on cloud devices like Saucelabs? Any documentation / steps around it?

**Comment by jlipps** [comment]
> How can we use unity-plugin for iOS platform?

The exact same way as for Android.

> Does this integration (Appium 2.0 & AltUnity server) works on cloud devices like Saucelabs? Any documentation / steps around it?

You would need to ask Saucelabs about that. the AltUnity server is inside your game so that is not an issue. But sauce labs would have to support this plugin and Appium 2.0, which I don't think they currently do.
